export const GET_ITEM_REQUEST = "GET_ITEM_REQUEST";
export const GET_ITEM_SUCESS = "GET_ITEM_SUCESS";
export const GET_ITEM_FAILURE = "GET_ITEM_FAILURE";

export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST";
export const ADD_ITEM_SUCESS = "ADD_ITEM_SUCESS";
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE";

export const DELETE_ITEM = "DELETE_ITEM";

export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST";
export const UPDATE_ITEM_SUCESS = "UPDATE_ITEM_SUCESS";
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE";
